In [1]:
import numpy as np
import math             

class BitString:
    """
    Simple class to implement a config of bits
    """
    def __init__(self, N):
        self.N = N
        self.config = np.zeros(N, dtype=int)
    
    def __str__(self):
        return f"{self.config}"
    
    def __eq__(self, other):        
        for values in zip(self.config, other.config):
            if values[0] != values[1]:
                return False
        return True
        
    def __len__(self):
        counter = 0
        for _ in self.config:
            counter += 1
        return counter
    
    def on(self):
        counter = 0
        for value in self.config:
            if value == 1:
                counter += 1
        return counter
    
    def off(self):
        counter = 0
        for value in self.config:
            if value == 0:
                counter += 1
        return counter
    
    def flip_site(self,i):
        self.config[i] = int(not self.config[i])
    
    def int(self):
        int_value = int("".join([str(i) for i in self.config]), 2)
        return int_value
        
    def set_config(self, s:list[int]):
        self.config = s
    
    def set_int_config(self, dec:int):
        bin_value = str(bin(dec))[2::]
        new_config = [value for value in bin_value]
        if len(new_config) != self.N:
            new_config = "".join(new_config)
            new_config = new_config.zfill(self.N)
        new_config = [int(value) for value in new_config]
        self.config = np.array(new_config)

def test1():
    my_bs = BitString(8)
    my_bs.flip_site(2)
    my_bs.flip_site(2)
    print(" The following should be 0:")
    print(my_bs)

    my_bs.flip_site(2)
    my_bs.flip_site(7)
    my_bs.flip_site(0)
    print(" The following should have 0,2,7 bits flipped:")
    print(my_bs)

    print(" Length of bitstring: ", len(my_bs))
    print(len(my_bs))
    assert(len(my_bs) == 8)

def test2():
    my_bs = BitString(13)
    my_bs.set_config([0,1,1,0,0,1,0,0,1,0,1,0,0])
    print(my_bs)

def test3():
    my_bs = BitString(13)
    my_bs.set_config([0,1,1,0,0,1,0,0,1,0,1,0,0])
    print(" on:  ", my_bs.on())
    print(" off: ", my_bs.off())
    assert(my_bs.on() == 5)
    assert(my_bs.off() == 8)

def test4():
    my_bs = BitString(13)
    my_bs.set_config([0,1,1,0,0,1,0,0,1,0,1,0,0])
    print(my_bs.int())
    assert(my_bs.int() == 3220)

def test5():
    my_bs = BitString(20)
    my_bs.set_int_config(3221)
    print(my_bs)

    # Let's make sure this worked:
    tmp = np.array([0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,1,0,1,0,1])
    assert((my_bs.config == tmp).all())

    # We can provide an even stronger test here:
    for i in range(1000):
        my_bs.set_int_config(i) # Converts from integer to binary
        assert(my_bs.int() == i) # Converts back from binary to integer and tests

def test6():
    my_bs1 = BitString(13)
    my_bs1.set_config([0,1,1,0,0,1,0,1,1,0,1,0,0])
    print(my_bs1, ": ", my_bs1.int())

    my_bs2 = BitString(13)
    my_bs2.set_int_config(3252)
    print(my_bs2, ": ", my_bs2.int())

    assert(my_bs1 == my_bs2)

    my_bs2.flip_site(5)
    assert(my_bs1 != my_bs2)

test1()
test2()
test3()
test4()
test5()
test6()

 The following should be 0:
[0 0 0 0 0 0 0 0]
 The following should have 0,2,7 bits flipped:
[1 0 1 0 0 0 0 1]
 Length of bitstring:  8
8
[0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0]
 on:   5
 off:  8
3220
[0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1]
[0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0] :  3252
[0 1 1 0 0 1 0 1 1 0 1 0 0] :  3252
