# BitString Class 

Write a Class that implements a bit representation that provides the functionality requested in the following questions.

In [51]:
import numpy as np
import math             

class BitString:
    """
    Simple class to implement a config of bits
    """
    def __init__(self, N):
        self.N = N
        self.config = np.zeros(N, dtype=int) 
        

    def __str__(self):
        return str(self.config)

    def __repr__(self):
        return f"Bitstring((self.config.tolist))"

    def __eq__(self, other):        
        return np.array_equal(self.config, other.config)

    
    def __len__(self):
        return len(self.config)


    def on(self):
        count = 0
        for i in self.config:
            if i == 1:
                count += 1
        return count
    
    def off(self):
        count = 0
        for i in self.config:
            if i == 0:
                count += 1
        return count
    
    def flip_site(self,i):
        self.config[i] = 1 - self.config[i]
        
    
    def int(self):
        dec = 0
        power = len(self.config) - 1  
        for i in self.config:
            dec = dec + i *(2**power) 
            power = power - 1
        return dec

 

    def set_config(self, s:list[int]):
        self.config = list(s)
        
    def set_int_config(self, dec:int):
        for i in range(-1,-self.N-1,-1):
          curr_bit = dec % 2 
          self.config[i]= curr_bit  
          dec = dec//2 
        return  self.config 
        
    


    





---

**1. Create an zero `BitString` of length 8 and flip a few bits and print the output.**

Methods needed:
- `__str__()`
- `flip()`
- `__len__()`

In [52]:
my_bs = BitString(8)
my_bs.flip_site(2)
my_bs.flip_site(2)
print(" The following should be 0:")
print(my_bs)

my_bs.flip_site(2)
my_bs.flip_site(7)
my_bs.flip_site(0)
print(" The following should have 0,2,7 bits flipped:")
print(my_bs)

print(" Length of bitstring: ", len(my_bs))
assert(len(my_bs) == 8)

 The following should be 0:
[0 0 0 0 0 0 0 0]
 The following should have 0,2,7 bits flipped:
[1 0 1 0 0 0 0 1]
 Length of bitstring:  8


---

**2. Add a method that lets you directly set the value of the bitstring by providing a string of 0s and 1s:**

Methods needed:
- `set_config()`

In [53]:
my_bs = BitString(13)
my_bs.set_config([0,1,1,0,0,1,0,0,1,0,1,0,0])
print(my_bs)

[0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0]


---

**3. Add a method that returns number of `on` bits and one that returns the number of `off` bits.**

Methods needed:
- `on()`
- `off()`

In [54]:
print(" on:  ", my_bs.on())
print(" off: ", my_bs.off())
assert(my_bs.on() == 5)
assert(my_bs.off() == 8)

 on:   5
 off:  8


---

**4. Add a method that returns the associated integer (decimal).**

Methods needed:
- `int()`

In [55]:
print(my_bs.int())
assert(my_bs.int() == 3220)

3220


---
**5. Add a method that lets you directly set the value of the bitstring by providing a decimal integer.** 

Also include  an optional keyword `digits` to let the user specify the length of the string.

Methods needed:
- `set_int_config()`

In [56]:
my_bs = BitString(20)
my_bs.set_int_config(3221)
print(my_bs)

# Let's make sure this worked:
tmp = np.array([0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,1,0,1,0,1])
assert((my_bs.config == tmp).all())

# We can provide an even stronger test here:
for i in range(1000):
    my_bs.set_int_config(i) # Converts from integer to binary
    assert(my_bs.int() == i) # Converts back from binary to integer and tests

[0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1]


---

**6. Overload equality operator**

Methods needed:
- `__eq__()`

In [57]:
my_bs1 = BitString(13)
my_bs1.set_config([0,1,1,0,0,1,0,1,1,0,1,0,0])
print(my_bs1, ": ", my_bs1.int())

my_bs2 = BitString(13)
my_bs2.set_int_config(3252)
print(my_bs2, ": ", my_bs2.int())


assert(my_bs1 == my_bs2)

my_bs2.flip_site(5)
assert(my_bs1 != my_bs2)

[0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0] :  3252
[0 1 1 0 0 1 0 1 1 0 1 0 0] :  3252
